---
# tasks file for bbaassssiiee.artifactory


- name: 'verify java -version'
  action: shell /usr/bin/java -version
  register: java
  changed_when: no
  tags:
    - verify

- assert:
    that:
      - "'version' in java.stderr"

- name: install prerequesites
  yum: name=openssl,unzip

- name: Create artifactory group
  group: name={{ artifactory_group}} state=present system=true

- name: 'create user to run artifactory'
  user: name={{artifactory_username}} groups={{ artifactory_group }} home=/opt/artifactory/ shell=/bin/bash system=true

#- copy: src=tmpfiles.d-artifactory.conf dest=/etc/tmpfiles.d/artifactory.conf
#  register: tmpfiles_result
#- command: systemd-tmpfiles --create --clean --prefix=/var/run/artifactory
#  when: tmpfiles_result.changed

- file: state=directory path=/var/cache/ansible

- name: 'verify presence of artifactory'
  stat: path="/opt/artifactory/artifactory-{{artifactory_version}}/webapps/artifactory.war"
  register: jarfile

- name: 'verify presence of artifactory_file'
  stat: path=/var/cache/ansible/{{artifactory_file}}
  register: download

- name: 'download artifactory'
  get_url: url={{artifactory_url}} dest=/var/cache/ansible/{{artifactory_file}}
  retries: 3
  when: not download.stat.exists

- name: 'unzip artifactory'
  command: unzip -o  /var/cache/ansible/{{artifactory_file}} -d /opt/artifactory
  when: not jarfile.stat.exists

- file: owner={{ artifactory_username }} group={{ artifactory_group }} recurse=yes path=/opt/artifactory follow=yes

- name: 'verify if an update is needed'
  shell: "ls -1d /opt/artifactory/artifactory-{{artifactory_license}}-* | grep -v artifactory-{{artifactory_license}}-{{artifactory_version}}"
  failed_when: false
  changed_when: false
  register: previous

- name: 'stop artifactory before upgrade'
  service: name=artifactory state=stopped
  when: previous.stdout

- name: 'move artifactory data folder'
  shell: mv {{ previous.stdout }}/data /opt/artifactory/artifactory-{{artifactory_license}}-{{artifactory_version}}
  notify: restart artifactory
  when: previous.stdout

- name: 'remove previous artifactory'
  file: dest={{ previous.stdout }} state=absent
  when: previous.stdout

#- name: 'verify presence of artifactory download'
#  stat: path=/var/cache/ansible/{{artifactory_file}}
#  register: artifactory_download

#- name: 'cleanup artifactory download'
#  file: dest=/var/cache/ansible/{{artifactory_file}} state=absent
#  when: artifactory_download.stat.exists

- name: 'create configuration file'
  template: src=etc-opt-jfrog-artifactory-default.j2 dest=/etc/sysconfig/artifactory owner=root group=root mode=0644

- name: 'symlink current version'
  file:
    state: link
    dest: "{{ artifactory_home }}"
    src: "/opt/artifactory/artifactory-{{artifactory_license}}-{{artifactory_version}}"
    owner: "{{ artifactory_username }}"
    group: "{{ artifactory_group }}"

- copy: src=empty dest={{ artifactory_home }}/bin/artifactory.default

#- name: 'install artifactory as a service'
#  command: "{{artifactory_home}}/bin/installService.sh {{artifactory_username}}"
#  notify:
#    - 'restart artifactory'

- name: 'create deploy script'
  template:
    src: deploy-file.sh 
    dest: /usr/local/bin/deploy-file.sh
    owner: "{{ artifactory_username }}"
    group: "{{ artifactory_username }}"
    mode: 0755

- template: src=artifactory.service dest=/etc/systemd/system/artifactory.service
  register: artifactory_service
- command: systemctl daemon-reload
  when: artifactory_service.changed
  notify:
    - 'restart artifactory'

- name: 'enable artifactory service'
  service: name=artifactory enabled=true state=started
