---
# features.mysql or features.postgresql should be true

# Download & install
- include_tasks: install.yml

# Database configuration, one or the other
- include_tasks: postgresql.yml
  when: artifactory_database == 'postgresql'
- include_tasks: mysql.yml
  when: artifactory_database == 'mysql'
